### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by jaymcguinness**
## Motivation

Fix typos.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/boyney123/eventcatalog/blob/main/CONTRIBUTING.md#pull-requests)?

Yup

### CODE REVIEW

**Comment by boyney123** [comment]
Thanks @jaymcguinness , for some reason some stages are failing (still working on the CI parts of this all), can you try run `yarn` and see if you get any lock file changes?

**Comment by jaymcguinness** [comment]
Ah - I just updated the readme on GitHub.  Will check it out properly in the morning.

**Comment by jaymcguinness** [comment]
Hi @boyney123 - there appear to be quite a few lock file changes.  I'm not familiar with yarn, so am hesitant to commit the yarn.lock file with so many version bumps (esp. as I'm on windows currently). Is this normal for yarn?

**Comment by boyney123** [comment]
@jaymcguinness yeah I pushed some changes up to master, try and rebase and go again... so if that fixed it.

Not sure about these lock file checks... but will keep them for now

**Comment by boyney123** [comment]
Thank you @jaymcguinness, all sorted! Thanks for the contribution 🤩

**Pull request merged**
