### PR TITLE
feat: configure favicon and set page title, description

### PR DESCRIPTION
**Pull request by thim81**
## Motivation

Linked to #129

Provide the option to set the favicon of the Event Catalog + use the title & tagline from the `eventcatalog.config.js` instead of the static defined text.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#pull-requests)?
yes

### CODE REVIEW

**Comment by boyney123** [comment]
Thanks @thim81 ,

The `favicon` in the config, do you have a scenario where you want to link it to another domain? EventCatalog supports letting you set the favicon by overriding the one in the `public` directory, is that possible for you?

**Comment by thim81** [comment]
> The `favicon` in the config, do you have a scenario where you want to link it to another domain? EventCatalog supports letting you set the favicon by overriding the one in the `public` directory, is that possible for you?

This would be OK, but I was not able to get that working properly.

If you want I can split this PR in 2 parts:
- favicon
- page title & description

**Comment by thim81** [comment]
on the favicon setting, I tried to put a custom favicon (favicon.ico & favicon.png) in the public folder but both were not used, in the generated output.

In the `<head>` section there is no reference towards the favicon.

2022-02-02 at 16 08 27

**Comment by boyney123** [comment]
Yeah let's split out the PR if that is OK, the title and description is a great idea.

That's weird the favicon does not work, I will have a look too! Think that was tested and working, maybe something broke, will take a look

**Comment by thim81** [comment]
@boyney123 I think I fixed the favicon issue while sorting out the meta data in PR #167

**Comment by thim81** [comment]
Closing this PR in favour of #167

**Pull request closed without merging**
