### PR TITLE
fix(schemas): Dont fail for schemas in custom registries

### PR DESCRIPTION
**Pull request by adlecluse**
## Motivation

Added a fix for https://github.com/boyney123/eventcatalog/issues/270 so it doesn't fail when it tries to download the schema from a custom registry.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Comment by boyney123** [comment]
Thank you @adlecluse makes sense to me!

**Comment by boyney123** [comment]
@all-contributors add @adlecluse for code

**Comment by boyney123** [comment]
Add you to list of contributors too :) thank you!

**Comment by IsmaelMartinez** [comment]
is this merged to master? I can see the same issue when following the installation/configuration steps. Thanks!

**Pull request merged**
