### PR TITLE
fix: render file asyncapi version 3.0.0

### PR DESCRIPTION
**Pull request by WaYdotNET**
## Motivation

fix render file asyncapi version 3.0.0

With file in `Account Service` folder (inside `services folder)

index.md
```markdown
---
name: Account Service
summary: |
   Account service summary.
---

Foo bar baz.

<AsyncAPI />

```

asyncapi.yaml
```yaml
asyncapi: 3.0.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  userSignedup:
    address: user/signedup
    messages:
      UserSignedUp:
        $ref: '#/components/messages/UserSignedUp'
operations:
  sendUserSignedup:
    action: send
    channel:
      $ref: '#/channels/userSignedup'
    messages:
      - $ref: '#/channels/userSignedup/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```

### Before fix
Screenshot 2024-01-20 at 15 58 04

### After fix

Screenshot 2024-01-20 at 15 56 38

### CODE REVIEW

**Comment by s1mrankaur** [comment]
+1. Waiting for this to be resolved. Version 3 AsyncAPI document cannot be embedded currently.

**Comment by boyney123** [comment]
Great thanks for this will release.

**Comment by boyney123** [comment]
@all-contributors add @WaYdotNET for code

**Comment by s1mrankaur** [comment]
@boyney123  @WaYdotNET  I gave this a go and while embedding a version 3 async API file worked, it does not work if there are $ref references to fragmented files. My  AsyncAPI files that I use to generate event catalogs have $refs to avoid channel and message duplication between producers and consumers. If event-catalog needs an asyncapi file without any $ref, what's the best way to go about it?

**Pull request merged**
