### PR TITLE
fix: Process asyncapi files with avro schema

### PR DESCRIPTION
**Pull request by gaddam1987**
This commit adds functionality to asyncapi-generator to process asyncapi files which has avro schema

## Motivation

I was planning to generate event-catalog from our asysnc files which uses avro. But i see that the current generator fails to process those so added that functionality.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### CODE REVIEW

**Comment by gaddam1987** [comment]
@boyney123 Is it possible to have look at it when ever you have time

**Comment by boyney123** [comment]
Sorry had a busy few weeks, just checked, thanks for adding this and also including the tests. Looking good to me, will merge and make a patch of the plugin. 

Let me know if things work or any issues. Looks good from what I can tell!

**Comment by boyney123** [comment]
Looks like the build is failing. https://github.com/boyney123/eventcatalog/actions/runs/5056838287/jobs/9074813948?pr=367#step:4:281

Any idea why?

**Comment by boyney123** [comment]
@all-contributors add @gaddam1987 for code

**Comment by boyney123** [comment]
Thanks @gaddam1987 will do a new release

**Pull request merged**
